language: python
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/app DBHOST=127.0.0.1 DBUSER=postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
  - docker
matrix:
  allow_failures:
    - os: osx
    - name: "Python 3.7.6 Linux (xenial)"
  include:
    - name: "Python 3.7.6 Linux (xenial)"
      os: linux
      python: 3.7-dev
    - name: "Python 3.6.7 Linux (xenial)"
      os: linux
      python: 3.6
      deploy:
        provider: script
        script: sh .travis/deploy_dockerhub.sh
    - name: "Python 3.7.4 on macOS (10.14.4)"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version ; pip3 --version ; sw_vers
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
      install:
        - python3 --version
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
      script:
        # unit test
        - python3 -m pytest -v tests/app_tests.py
        - flake8 --exit-zero --exclude venv/ .
install:
  - date
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - psql -c 'DROP DATABASE IF EXISTS pyted;' -U postgres
  - psql -c 'create database pyted;' -U postgres
  - psql -h 127.0.0.1 -U postgres -d pyted < sql/test_data.sql
script:
  # unit test
  - python -m pytest -v tests/app_tests.py
  - flake8 --exit-zero --exclude venv/ .