version: '3.3'

services:
   db:
     image: postgres:12.1
     restart: always
     environment:
       POSTGRES_DB: pyted
       POSTGRES_USER: pyted
       POSTGRES_PASSWORD: password

   pyted:
     depends_on:
       - db
     image: ch0ppy35/pyted
     ports:
       - "5000:5000"
     restart: always
     environment:
       DBHOST: db
       DBUSER: pyted
       DBPASS: password
       DOCKER: 'True'