version: '3.3'

services:
   db:
     image: postgres:12.1
     ports:
       - "5432:5432"
     restart: always
     environment:
       POSTGRES_DB: pyted
       POSTGRES_USER: pyted
       POSTGRES_PASSWORD: password

   pyted:
     depends_on:
       - db
     image: ch0ppy35/pyted
     ports:
       - "5000:5000"
     restart: always
     environment:
       DBHOST: db
       DBUSER: pyted
       DBDB: pyted
       METERREAD: 10
       COST: 0.06
       TZ: AMERICA/NEW_YORK
       DBPASS: password
       #DOCKER: 'True'
       HOST: ***REMOVED***